# Generated by Django 5.0.2 on 2024-03-10 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parkingspace',
            name='price',
        ),
        migrations.AlterField(
            model_name='sale',
            name='price',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parking.price'),
        ),
    ]
