# Generated by Django 5.0.2 on 2024-03-12 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0005_remove_sale_is_purchased_remove_sale_rented_before_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='price',
        ),
        migrations.AddField(
            model_name='sale',
            name='price_amaunt',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='promo_code',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='rent_from',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='sale',
            name='rent_to',
            field=models.DateField(),
        ),
    ]
