# Generated by Django 5.0.2 on 2024-03-03 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=128, null=True)),
                ('phone_number', models.CharField(max_length=12, unique=True)),
                ('otp', models.PositiveIntegerField()),
                ('session_token', models.CharField(max_length=500, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Коды',
                'verbose_name_plural': 'Коды',
                'ordering': ('-id',),
            },
        ),
    ]
