# Generated by Django 5.0.2 on 2024-03-02 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smscode', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='session_token',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
